version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front_app
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    networks:
      - front_net

  nginx:
    image: nginx:alpine
    container_name: front_nginx
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    depends_on:
      - front
    networks:
      - front_net

networks:
  front_net:
